//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUT_M {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_fr() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CUT_M.Lang_fr", typeof(Lang_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adam 1 non connecté.
        /// </summary>
        internal static string Adam1NotConnected {
            get {
                return ResourceManager.GetString("Adam1NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annulation production.
        /// </summary>
        internal static string btAnnule {
            get {
                return ResourceManager.GetString("btAnnule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez une référence.
        /// </summary>
        internal static string ChoisirRef {
            get {
                return ResourceManager.GetString("ChoisirRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir ou saisir une référence.
        /// </summary>
        internal static string ChoixRef {
            get {
                return ResourceManager.GetString("ChoixRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez fermer la porte et ouvrir le shutter..
        /// </summary>
        internal static string CloseAndStart {
            get {
                return ResourceManager.GetString("CloseAndStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connecté au module Adam 1.
        /// </summary>
        internal static string ConnectAdam1 {
            get {
                return ResourceManager.GetString("ConnectAdam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connecté au module Adam 2.
        /// </summary>
        internal static string ConnectAdam2 {
            get {
                return ResourceManager.GetString("ConnectAdam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à J&apos;ai lu les consignes ci-dessous.
        /// </summary>
        internal static string Consigne {
            get {
                return ResourceManager.GetString("Consigne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Découpe en cours.
        /// </summary>
        internal static string Decoupe {
            get {
                return ResourceManager.GetString("Decoupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Découpe terminée.
        /// </summary>
        internal static string DecoupeTermine {
            get {
                return ResourceManager.GetString("DecoupeTermine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Démarrage découpe.
        /// </summary>
        internal static string DemarrageDecoupe {
            get {
                return ResourceManager.GetString("DemarrageDecoupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En attente chargement capot et départ cycle.
        /// </summary>
        internal static string DepartCycle {
            get {
                return ResourceManager.GetString("DepartCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fermée.
        /// </summary>
        internal static string Fermee {
            get {
                return ResourceManager.GetString("Fermee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fermer la porte.
        /// </summary>
        internal static string FermerPorte {
            get {
                return ResourceManager.GetString("FermerPorte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialisation module Adam 1 OK.
        /// </summary>
        internal static string InitAdam1 {
            get {
                return ResourceManager.GetString("InitAdam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialisation module Adam 2 OK.
        /// </summary>
        internal static string InitAdam2 {
            get {
                return ResourceManager.GetString("InitAdam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations.
        /// </summary>
        internal static string lblInfos {
            get {
                return ResourceManager.GetString("lblInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Production en cours.
        /// </summary>
        internal static string lblProd {
            get {
                return ResourceManager.GetString("lblProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Référence à partir du fichier.
        /// </summary>
        internal static string lblRef {
            get {
                return ResourceManager.GetString("lblRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diamètre.
        /// </summary>
        internal static string lblTitreDiametre {
            get {
                return ResourceManager.GetString("lblTitreDiametre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N° étage mandrin.
        /// </summary>
        internal static string lblTitreEtage {
            get {
                return ResourceManager.GetString("lblTitreEtage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etat.
        /// </summary>
        internal static string lblTitreEtat {
            get {
                return ResourceManager.GetString("lblTitreEtat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Laser :.
        /// </summary>
        internal static string lbltitreLaser {
            get {
                return ResourceManager.GetString("lbltitreLaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Porte :.
        /// </summary>
        internal static string lbltitrePorte {
            get {
                return ResourceManager.GetString("lbltitrePorte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quantité restante.
        /// </summary>
        internal static string lblTitreQte {
            get {
                return ResourceManager.GetString("lblTitreQte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement du masque.
        /// </summary>
        internal static string LoadMask {
            get {
                return ResourceManager.GetString("LoadMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialisation module Adam 1 impossible.
        /// </summary>
        internal static string NoConnectAdam1 {
            get {
                return ResourceManager.GetString("NoConnectAdam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialisation module Adam 2 impossible.
        /// </summary>
        internal static string NoConnectAdam2 {
            get {
                return ResourceManager.GetString("NoConnectAdam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune référence disponible.
        /// </summary>
        internal static string NoRef {
            get {
                return ResourceManager.GetString("NoRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir la porte.
        /// </summary>
        internal static string OuvrirPorte {
            get {
                return ResourceManager.GetString("OuvrirPorte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir le shutter.
        /// </summary>
        internal static string OuvrirShutter {
            get {
                return ResourceManager.GetString("OuvrirShutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Positionner la pièce.
        /// </summary>
        internal static string PlacerPiece {
            get {
                return ResourceManager.GetString("PlacerPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fermer.
        /// </summary>
        internal static string Quitter {
            get {
                return ResourceManager.GetString("Quitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timer 1 démarré.
        /// </summary>
        internal static string Timer1Start {
            get {
                return ResourceManager.GetString("Timer1Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timer 2 démarré.
        /// </summary>
        internal static string Timer2Start {
            get {
                return ResourceManager.GetString("Timer2Start", resourceCulture);
            }
        }
    }
}
